# CodeRabbit configuration
# Auto-merge disabled as per project policy
version: 1
auto_merge: false

review:
  # Define review classes to route comments to relevant areas
  classes:
    - name: ui
      patterns:
        - 'client/ui/**'
    - name: client
      patterns:
        - 'client/**'
        - '!client/ui/**'
    - name: server
      patterns:
        - 'server/**'
    - name: audio
      patterns:
        - 'client/audio/**'
        - 'server/audio/**'
    - name: security
      patterns:
        - '**/*.py'
    - name: quality
      patterns:
        - '**/*.py'
  # General rules
  rules:
    - id: python-quality
      languages: [python]
      severity: info
      enabled: true
    - id: python-security
      languages: [python]
      severity: warning
      enabled: true

notifications:
  # Placeholder notification settings; adjust to your team
  pull_request_comments: true
  summary: true
