name: CodeRabbit Review and Testing

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  coderabbit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run static checks
        run: |
          echo "Running static analysis..."
          python -m py_compile server/main_server.py client/main_client.py
          python -m py_compile client/video/*.py server/video/*.py
          python -m py_compile client/audio/*.py server/audio/*.py
          echo "✅ All files compile successfully"

      - name: Test imports
        run: |
          echo "Testing imports..."
          python -c "from common import constants, protocol_definitions; print('✅ Common modules OK')"
          python -c "from client.video import video_client, video_viewer; print('✅ Video modules OK')"
          python -c "from client.audio import audio_client; print('✅ Audio module OK')"
          python -c "from server import main_server; print('✅ Server module OK')"
          echo "✅ All imports successful"

      - name: Verify help commands
        run: |
          echo "Testing --help commands..."
          python server/main_server.py --help > /dev/null && echo "✅ Server help OK"
          python client/video/video_client.py --help > /dev/null && echo "✅ Video client help OK"
          python client/audio/audio_client.py --help > /dev/null && echo "✅ Audio client help OK"
          python server/video/video_server.py --help > /dev/null && echo "✅ Video server help OK"

      - name: Check code quality
        run: |
          echo "Checking code quality..."
          # Install flake8 if not available
          python -c "import flake8" 2>/dev/null || pip install flake8
          # Run flake8 linting on the codebase
          python -m flake8 . --max-line-length=120 --extend-ignore=E203,W503 --exclude=__pycache__,venv,env,.git

      - name: Summary
        run: |
          echo "=========================================="
          echo "✅ CODE RABBIT REVIEW COMPLETE"
          echo "=========================================="
          echo "✅ Static checks passed"
          echo "✅ Imports verified"
          echo "✅ Help commands work"
          echo "=========================================="
          echo "Ready for integration testing"
